"""
SQLModel models for the Item entity.

MODEL TYPES EXPLAINED:
----------------------
1. Base Model: Shared fields used by other models (no table, no id)
2. Table Model: The actual database table (has table=True and id)
3. Create Model: For POST requests (no id - database generates it)
4. Read Model: For responses (includes id)
5. Update Model: For PATCH requests (all fields optional)

This pattern is called "Multiple Models" and helps with:
- Security: Don't expose internal fields
- Validation: Different rules for create vs update
- Clarity: Each model has a clear purpose
"""

from sqlmodel import Field, SQLModel


# =============================================================================
# BASE MODEL - Shared fields
# =============================================================================
class ItemBase(SQLModel):
    """
    Base model with fields shared across all Item models.

    This is NOT a database table (no table=True).
    Other models inherit from this to avoid repeating fields.
    """

    name: str = Field(index=True)  # index=True makes searches faster
    description: str | None = Field(default=None)
    price: float = Field(gt=0)  # gt=0 means price must be greater than 0
    is_available: bool = Field(default=True)


# =============================================================================
# TABLE MODEL - The actual database table
# =============================================================================
class Item(ItemBase, table=True):
    """
    The database table model.

    - table=True tells SQLModel to create a database table for this
    - id is the primary key, auto-generated by the database
    - Inherits all fields from ItemBase
    """

    id: int | None = Field(default=None, primary_key=True)


# =============================================================================
# CREATE MODEL - For POST requests
# =============================================================================
class ItemCreate(ItemBase):
    """
    Model for creating new items.

    - No 'id' field (database generates it)
    - Inherits required fields from ItemBase
    - Used as request body type in POST endpoint
    """

    pass  # All fields come from ItemBase


# =============================================================================
# READ MODEL - For responses
# =============================================================================
class ItemRead(ItemBase):
    """
    Model for reading/returning items.

    - Includes 'id' since it exists after creation
    - Used as response_model in endpoints
    """

    id: int


# =============================================================================
# UPDATE MODEL - For PATCH requests
# =============================================================================
class ItemUpdate(SQLModel):
    """
    Model for updating items.

    - All fields are OPTIONAL (user can update just one field)
    - Does NOT inherit from ItemBase (we want all fields optional)
    - Used for partial updates (PATCH, not PUT)
    """

    name: str | None = None
    description: str | None = None
    price: float | None = Field(default=None, gt=0)
    is_available: bool | None = None
